"use client";
import { useState, createContext, useContext, useEffect } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const NavbarContext = createContext("");

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [currTab, setCurrTab] = useState("");

  useEffect(() => {
    setCurrTab(window.location.pathname.split("/")[3]);
    console.log(window.location.pathname.split("/")[3]);
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarContext.Provider value={currTab}>
          <Navbar />
        </NavbarContext.Provider>
        <main>{children}</main>
      </body>
    </html>
  );
}
