import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import NavbarV2 from "@/Components/NavbarV2";
import { getSession } from "next-auth/react";
import SessionProvider from "@/Components/SessionProvider";
import { SpeedInsights } from "@vercel/speed-insights/next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className="bg-primary">
        <SessionProvider session={session}>
          {/* <Navbar /> */}
          <NavbarV2 />
          <main className="bg-primary">{children}</main>
          <SpeedInsights />
        </SessionProvider>
      </body>
    </html>
  );
}
